resolver: lts-13.28
flags: {}

packages:
- reinforce
- reinforce-algorithms
- reinforce-environments
- reinforce-environments-gym
- reinforce-zoo

# extra-lib-dirs:
# - /usr/local/lib/
# - /compat/linux/lib/

# extra-include-dirs:
# - /usr/local/include/

nix:
  packages: [ libGL libGLU freeglut ]

